//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }

        public int IDCus { get; set; }
        public int CodeCus { get; set; }
        public string EmailCus { get; set; }
        public string AddressCus { get; set; }
        public string PhoneCus { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}